// <auto-generated />
using System;
using BHYT.API.Models.DbModels;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BHYT.API.Migrations
{
    [DbContext(typeof(BHYTDbContext))]
    [Migration("20231202161039_testInsert1")]
    partial class testInsert1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BHYT.API.Models.DbModels.Benefit", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    b.Property<string>("Description")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("DESCRIPTION");

                    b.Property<Guid?>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("GUID")
                        .HasDefaultValueSql("(newid())");

                    b.Property<string>("Name")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("NAME");

                    b.HasKey("Id")
                        .HasName("BENEFIT_PK");

                    b.HasIndex(new[] { "Guid" }, "UQ__BENEFIT__15B69B8F92DB0273")
                        .IsUnique()
                        .HasFilter("[GUID] IS NOT NULL");

                    b.HasIndex(new[] { "Guid" }, "idx_GUID");

                    b.ToTable("BENEFIT", (string)null);
                });

            modelBuilder.Entity("BHYT.API.Models.DbModels.Compensation", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    b.Property<double?>("Amount")
                        .HasColumnType("float")
                        .HasColumnName("AMOUNT");

                    b.Property<DateTime?>("Date")
                        .HasColumnType("date")
                        .HasColumnName("DATE");

                    b.Property<int?>("EmployeeId")
                        .HasColumnType("int")
                        .HasColumnName("EMPLOYEE_ID");

                    b.Property<Guid?>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("GUID")
                        .HasDefaultValueSql("(newid())");

                    b.Property<string>("Note")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("NOTE");

                    b.Property<int?>("PolicyId")
                        .HasColumnType("int")
                        .HasColumnName("POLICY_ID");

                    b.Property<bool?>("Status")
                        .HasColumnType("bit")
                        .HasColumnName("STATUS");

                    b.HasKey("Id")
                        .HasName("COMPENSATION_PK");

                    b.HasIndex(new[] { "Guid" }, "UQ__COMPENSA__15B69B8F37DC82A4")
                        .IsUnique()
                        .HasFilter("[GUID] IS NOT NULL");

                    b.HasIndex(new[] { "Guid" }, "idx_GUID");

                    b.ToTable("COMPENSATION", (string)null);
                });

            modelBuilder.Entity("BHYT.API.Models.DbModels.Customer", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    b.Property<string>("Address")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("ADDRESS");

                    b.Property<string>("Bank")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("BANK");

                    b.Property<string>("BankNumber")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("BANK_NUMBER");

                    b.Property<DateTime?>("Birthday")
                        .HasColumnType("date")
                        .HasColumnName("BIRTHDAY");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("EMAIL");

                    b.Property<string>("Fullname")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("FULLNAME");

                    b.Property<Guid?>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("GUID")
                        .HasDefaultValueSql("(newid())");

                    b.Property<string>("Password")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("PASSWORD");

                    b.Property<string>("Phone")
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)")
                        .HasColumnName("PHONE");

                    b.Property<int?>("RoleId")
                        .HasColumnType("int")
                        .HasColumnName("ROLE_ID");

                    b.Property<int?>("Sex")
                        .HasColumnType("int")
                        .HasColumnName("SEX");

                    b.Property<int?>("StatusId")
                        .HasColumnType("int")
                        .HasColumnName("STATUS_ID");

                    b.Property<string>("Username")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("USERNAME");

                    b.HasKey("Id")
                        .HasName("CUSTOMER_PK");

                    b.HasIndex(new[] { "Guid" }, "UQ__CUSTOMER__15B69B8F12620E9E")
                        .IsUnique()
                        .HasFilter("[GUID] IS NOT NULL");

                    b.HasIndex(new[] { "Guid" }, "idx_GUID");

                    b.ToTable("CUSTOMER", (string)null);
                });

            modelBuilder.Entity("BHYT.API.Models.DbModels.CustomerPolicy", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    b.Property<int?>("BenefitId")
                        .HasColumnType("int")
                        .HasColumnName("BENEFIT_ID");

                    b.Property<string>("Company")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("COMPANY");

                    b.Property<string>("CoverageType")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("COVERAGE_TYPE");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("date")
                        .HasColumnName("CREATED_DATE");

                    b.Property<int?>("CustomerId")
                        .HasColumnType("int")
                        .HasColumnName("CUSTOMER_ID");

                    b.Property<double?>("DeductibleAmount")
                        .HasColumnType("float")
                        .HasColumnName("DEDUCTIBLE_AMOUNT");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("DESCRIPTION");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("date")
                        .HasColumnName("END_DATE");

                    b.Property<Guid?>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("GUID")
                        .HasDefaultValueSql("(newid())");

                    b.Property<int?>("InsuranceId")
                        .HasColumnType("int")
                        .HasColumnName("INSURANCE_ID");

                    b.Property<DateTime?>("LatestUpdate")
                        .HasColumnType("date")
                        .HasColumnName("LATEST_UPDATE");

                    b.Property<bool?>("PaymentOption")
                        .HasColumnType("bit")
                        .HasColumnName("PAYMENT_OPTION");

                    b.Property<double?>("PremiumAmount")
                        .HasColumnType("float")
                        .HasColumnName("PREMIUM_AMOUNT");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("date")
                        .HasColumnName("START_DATE");

                    b.Property<bool?>("Status")
                        .HasColumnType("bit")
                        .HasColumnName("STATUS");

                    b.HasKey("Id")
                        .HasName("CUSTOMER_POLICIES_PK");

                    b.HasIndex(new[] { "Guid" }, "UQ__CUSTOMER__15B69B8FBD3D10F9")
                        .IsUnique()
                        .HasFilter("[GUID] IS NOT NULL");

                    b.HasIndex(new[] { "Guid" }, "idx_GUID");

                    b.ToTable("CUSTOMER_POLICIES", (string)null);
                });

            modelBuilder.Entity("BHYT.API.Models.DbModels.Employee", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    b.Property<string>("Address")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("ADDRESS");

                    b.Property<DateTime?>("Birthday")
                        .HasColumnType("date")
                        .HasColumnName("BIRTHDAY");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("EMAIL");

                    b.Property<string>("Fullname")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("FULLNAME");

                    b.Property<Guid?>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("GUID")
                        .HasDefaultValueSql("(newid())");

                    b.Property<string>("Password")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("PASSWORD");

                    b.Property<string>("Phone")
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)")
                        .HasColumnName("PHONE");

                    b.Property<int?>("RoleId")
                        .HasColumnType("int")
                        .HasColumnName("ROLE_ID");

                    b.Property<int?>("Sex")
                        .HasColumnType("int")
                        .HasColumnName("SEX");

                    b.Property<int?>("StatusId")
                        .HasColumnType("int")
                        .HasColumnName("STATUS_ID");

                    b.Property<string>("Username")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("USERNAME");

                    b.HasKey("Id")
                        .HasName("EMPLOYEE_PK");

                    b.HasIndex(new[] { "Guid" }, "UQ__EMPLOYEE__15B69B8FBFD72589")
                        .IsUnique()
                        .HasFilter("[GUID] IS NOT NULL");

                    b.HasIndex(new[] { "Guid" }, "idx_GUID");

                    b.ToTable("EMPLOYEE", (string)null);
                });

            modelBuilder.Entity("BHYT.API.Models.DbModels.HealthHistory", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    b.Property<string>("Condition")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("CONDITION");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("date")
                        .HasColumnName("CREATED_DATE");

                    b.Property<int?>("CustomerId")
                        .HasColumnType("int")
                        .HasColumnName("CUSTOMER_ID");

                    b.Property<string>("Detail")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("DETAIL");

                    b.Property<string>("Diagnostic")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("DIAGNOSTIC");

                    b.Property<Guid?>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("GUID")
                        .HasDefaultValueSql("(newid())");

                    b.Property<string>("HospitalNumber")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("HOSPITAL_NUMBER");

                    b.Property<int?>("InsuranceId")
                        .HasColumnType("int")
                        .HasColumnName("INSURANCE_ID");

                    b.Property<string>("Note")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("NOTE");

                    b.HasKey("Id")
                        .HasName("HEALTH_HISTORY_PK");

                    b.HasIndex(new[] { "Guid" }, "UQ__HEALTH_H__15B69B8FAD12E3E0")
                        .IsUnique()
                        .HasFilter("[GUID] IS NOT NULL");

                    b.HasIndex(new[] { "Guid" }, "idx_GUID");

                    b.ToTable("HEALTH_HISTORY", (string)null);
                });

            modelBuilder.Entity("BHYT.API.Models.DbModels.Insurance", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    b.Property<string>("Description")
                        .HasMaxLength(300)
                        .IsUnicode(false)
                        .HasColumnType("varchar(300)")
                        .HasColumnName("DESCRIPTION");

                    b.Property<byte?>("EndAge")
                        .HasColumnType("tinyint")
                        .HasColumnName("END_AGE");

                    b.Property<Guid?>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("GUID")
                        .HasDefaultValueSql("(newid())");

                    b.Property<string>("InsuranceTypeId")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("INSURANCE_TYPE_ID");

                    b.Property<string>("Name")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("NAME");

                    b.Property<byte?>("StartAge")
                        .HasColumnType("tinyint")
                        .HasColumnName("START_AGE");

                    b.HasKey("Id")
                        .HasName("INSURANCE_PK");

                    b.HasIndex(new[] { "Guid" }, "UQ__INSURANC__15B69B8FDF297966")
                        .IsUnique()
                        .HasFilter("[GUID] IS NOT NULL");

                    b.HasIndex(new[] { "Guid" }, "idx_GUID");

                    b.ToTable("INSURANCE", (string)null);
                });

            modelBuilder.Entity("BHYT.API.Models.DbModels.InsurancePayment", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    b.Property<double?>("Amount")
                        .HasColumnType("float")
                        .HasColumnName("AMOUNT");

                    b.Property<int?>("CustomerId")
                        .HasColumnType("int")
                        .HasColumnName("CUSTOMER_ID");

                    b.Property<DateTime?>("Date")
                        .HasColumnType("date")
                        .HasColumnName("DATE");

                    b.Property<Guid?>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("GUID")
                        .HasDefaultValueSql("(newid())");

                    b.Property<string>("Note")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("NOTE");

                    b.Property<int?>("PolicyId")
                        .HasColumnType("int")
                        .HasColumnName("POLICY_ID");

                    b.Property<bool?>("Status")
                        .HasColumnType("bit")
                        .HasColumnName("STATUS");

                    b.Property<string>("Type")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("TYPE");

                    b.HasKey("Id")
                        .HasName("INSURANCE_PAYMENT_PK");

                    b.HasIndex(new[] { "Guid" }, "UQ__INSURANC__15B69B8F6483C5CF")
                        .IsUnique()
                        .HasFilter("[GUID] IS NOT NULL");

                    b.HasIndex(new[] { "Guid" }, "idx_GUID");

                    b.ToTable("INSURANCE_PAYMENT", (string)null);
                });

            modelBuilder.Entity("BHYT.API.Models.DbModels.InsuranceRequired", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    b.Property<double?>("Amount")
                        .HasColumnType("float")
                        .HasColumnName("AMOUNT");

                    b.Property<DateTime?>("Date")
                        .HasColumnType("date")
                        .HasColumnName("DATE");

                    b.Property<Guid?>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("GUID")
                        .HasDefaultValueSql("(newid())");

                    b.Property<string>("MedicalServiceName")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("MEDICAL_SERVICE_NAME");

                    b.Property<string>("Note")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("NOTE");

                    b.Property<int?>("PolicyId")
                        .HasColumnType("int")
                        .HasColumnName("POLICY_ID");

                    b.Property<string>("ServiceDescription")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("SERVICE_DESCRIPTION");

                    b.Property<int?>("Status")
                        .HasColumnType("int")
                        .HasColumnName("STATUS");

                    b.HasKey("Id")
                        .HasName("INSURANCE_REQUIRED_PK");

                    b.HasIndex(new[] { "Guid" }, "UQ__INSURANC__15B69B8F061E3A3B")
                        .IsUnique()
                        .HasFilter("[GUID] IS NOT NULL");

                    b.HasIndex(new[] { "Guid" }, "idx_GUID");

                    b.ToTable("INSURANCE_REQUIRED", (string)null);
                });

            modelBuilder.Entity("BHYT.API.Models.DbModels.InsuranceType", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("DESCRIPTION");

                    b.Property<Guid?>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("GUID")
                        .HasDefaultValueSql("(newid())");

                    b.Property<string>("Name")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("NAME");

                    b.HasKey("Id")
                        .HasName("INSURANCE_TYPE_PK");

                    b.HasIndex(new[] { "Guid" }, "UQ__INSURANC__15B69B8F8ABB27D4")
                        .IsUnique()
                        .HasFilter("[GUID] IS NOT NULL");

                    b.HasIndex(new[] { "Guid" }, "idx_GUID");

                    b.ToTable("INSURANCE_TYPE", (string)null);
                });

            modelBuilder.Entity("BHYT.API.Models.DbModels.PolicyApproval", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    b.Property<DateTime?>("ApprovalDate")
                        .HasColumnType("date")
                        .HasColumnName("APPROVAL_DATE");

                    b.Property<int?>("EmployeeId")
                        .HasColumnType("int")
                        .HasColumnName("EMPLOYEE_ID");

                    b.Property<Guid?>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("GUID")
                        .HasDefaultValueSql("(newid())");

                    b.Property<int?>("PolicyId")
                        .HasColumnType("int")
                        .HasColumnName("POLICY_ID");

                    b.Property<int?>("StatusId")
                        .HasColumnType("int")
                        .HasColumnName("STATUS_ID");

                    b.HasKey("Id")
                        .HasName("POLICY_APPROVAL_PK");

                    b.HasIndex(new[] { "Guid" }, "UQ__POLICY_A__15B69B8FFD1FBDBA")
                        .IsUnique()
                        .HasFilter("[GUID] IS NOT NULL");

                    b.HasIndex(new[] { "Guid" }, "idx_GUID");

                    b.ToTable("POLICY_APPROVAL", (string)null);
                });

            modelBuilder.Entity("BHYT.API.Models.DbModels.ResetPasswordRequest", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    b.Property<string>("Accountid")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("ACCOUNTID");

                    b.Property<Guid?>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("GUID")
                        .HasDefaultValueSql("(newid())");

                    b.Property<DateTime?>("Requestdate")
                        .HasColumnType("datetime")
                        .HasColumnName("REQUESTDATE");

                    b.Property<DateTime?>("Resetdate")
                        .HasColumnType("datetime")
                        .HasColumnName("RESETDATE");

                    b.Property<string>("Resetrequestcode")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("RESETREQUESTCODE");

                    b.HasKey("Id")
                        .HasName("RESET_PASSWORD_REQUEST_PK");

                    b.HasIndex(new[] { "Guid" }, "UQ__RESET_PA__15B69B8F0CE555AB")
                        .IsUnique()
                        .HasFilter("[GUID] IS NOT NULL");

                    b.HasIndex(new[] { "Guid" }, "idx_GUID");

                    b.ToTable("RESET_PASSWORD_REQUEST", (string)null);
                });

            modelBuilder.Entity("BHYT.API.Models.DbModels.Role", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    b.Property<Guid?>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("GUID")
                        .HasDefaultValueSql("(newid())");

                    b.Property<string>("Name")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("NAME");

                    b.HasKey("Id")
                        .HasName("ROLE_PK");

                    b.HasIndex(new[] { "Guid" }, "UQ__ROLE__15B69B8FAB73D4EE")
                        .IsUnique()
                        .HasFilter("[GUID] IS NOT NULL");

                    b.HasIndex(new[] { "Guid" }, "idx_GUID");

                    b.ToTable("ROLE", (string)null);
                });

            modelBuilder.Entity("BHYT.API.Models.DbModels.Session", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    b.Property<string>("AccountId")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("ACCOUNT_ID");

                    b.Property<string>("Appversion")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("APPVERSION");

                    b.Property<Guid?>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("GUID")
                        .HasDefaultValueSql("(newid())");

                    b.Property<int?>("IsValid")
                        .HasColumnType("int")
                        .HasColumnName("IS_VALID");

                    b.Property<DateTime?>("LOginDate")
                        .HasColumnType("date")
                        .HasColumnName("lOGIN_DATE");

                    b.Property<string>("ServiceDescription")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("SERVICE_DESCRIPTION");

                    b.Property<string>("SessionLastIp")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("SESSION_LAST_IP");

                    b.Property<DateTime?>("SessionLastRefresh")
                        .HasColumnType("date")
                        .HasColumnName("SESSION_LAST_REFRESH");

                    b.Property<string>("SessionToken")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("SESSION_TOKEN");

                    b.HasKey("Id")
                        .HasName("SESSION_PK");

                    b.HasIndex(new[] { "Guid" }, "UQ__SESSION__15B69B8FE2E4485C")
                        .IsUnique()
                        .HasFilter("[GUID] IS NOT NULL");

                    b.HasIndex(new[] { "Guid" }, "idx_GUID");

                    b.ToTable("SESSION", (string)null);
                });

            modelBuilder.Entity("BHYT.API.Models.DbModels.Status", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    b.Property<Guid?>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("GUID")
                        .HasDefaultValueSql("(newid())");

                    b.Property<bool?>("Name")
                        .HasColumnType("bit")
                        .HasColumnName("NAME");

                    b.HasKey("Id")
                        .HasName("STATUS_PK");

                    b.HasIndex(new[] { "Guid" }, "UQ__STATUS__15B69B8F10330BE7")
                        .IsUnique()
                        .HasFilter("[GUID] IS NOT NULL");

                    b.HasIndex(new[] { "Guid" }, "idx_GUID");

                    b.ToTable("STATUS", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
